# Generated by Django 4.2.19 on 2025-02-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
    ]
