# Generated by Django 5.1.6 on 2025-02-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='two_fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='two_fa_verified',
            field=models.BooleanField(default=False),
        ),
    ]
