# Generated by Django 5.1.6 on 2025-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0002_player_two_fa_enabled_player_two_fa_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='two_fa_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
