# Generated by Django 5.1.6 on 2025-02-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0003_player_two_fa_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='two_fa_secret',
        ),
    ]
