# Generated by Django 5.1.6 on 2025-03-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0004_remove_player_two_fa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='_two_fa_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
