services:
  databaseapi:
    depends_on:
      database:
        condition: service_healthy
    container_name: ctn_databaseapi
    build :
      context: ../
      dockerfile: _docker/Dockerfile
    environment:
      env: prod
      name: databaseapi
      port: $databaseapi_port
      HOST_IP: $HOST_IP
      DJANGO_SETTINGS_MODULE: databaseapi.settings
    env_file:
      - ../../.env
    image: img_databaseapi
    networks:
      - transcendence_network
    volumes:
      - staticvol:/app/staticfiles
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:${databaseapi_port}/health/ > /dev/null 2>&1"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 60s
    restart: always