services:
  tournament:
    container_name: ctn_tournament
    build :
      context: ../
      dockerfile: _docker/Dockerfile
    environment:
      env: prod
      name: tournament
      port: $tournament_port
      HOST_IP: $HOST_IP
      rasp: $rasp
      DJANGO_SETTINGS_MODULE: tournament.settings
    env_file:
      - ../../.env
    image: img_tournament
    networks:
      - transcendence_network
    volumes:
      - staticvol:/app/staticfiles
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:${tournament_port}/health/ > /dev/null 2>&1"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 60s
    restart: always