services:
  match:
    container_name: ctn_match
    build :
      context: ../
      dockerfile: _docker/Dockerfile
    environment:
      env: prod
      name: match
      port: $match_port
      HOST_IP: $HOST_IP
      rasp: $rasp
      DJANGO_SETTINGS_MODULE: match.settings
    env_file:
      - ../../.env
    image: img_match
    networks:
      - transcendence_network
    volumes:
      - staticvol:/app/staticfiles
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:${match_port}/health/ > /dev/null 2>&1"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 60s
    restart: always