# Generated by Django 4.2.19 on 2025-02-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDummyModelAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_dummy', models.CharField(max_length=100)),
                ('name_dummy_2', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
