# Generated by Django 4.2.19 on 2025-02-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdummymodelauth',
            name='name_dummy_2',
        ),
    ]
