# Generated by Django 5.1.6 on 2025-02-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0004_player_is_active_alter_player_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={},
        ),
    ]
