# Generated by Django 5.1.6 on 2025-02-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_app', '0002_player_tournament_match_delete_matchdummymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
    ]
