-- USERS SERVICE
CREATE SCHEMA [IF NOT EXISTS] user_schema;

-- MATCH-MACKING
CREATE SCHEMA [IF NOT EXISTS] match_schema;


-- FRIENDSHIP SERVICE
CREATE SCHEMA [IF NOT EXISTS] friendship_schema;



-- TOURNAMENT
CREATE SCHEMA [IF NOT EXISTS] tournament_schema;