# Generated by Django 5.1.7 on 2025-03-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='match',
            table='match',
        ),
        migrations.AlterModelTable(
            name='player',
            table='player',
        ),
    ]
