# Generated by Django 5.1.7 on 2025-04-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapi_app', '0002_playerstatistics_match_end_time_match_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='start_time',
        ),
        migrations.DeleteModel(
            name='PlayerStatistics',
        ),
    ]
