# Generated by Django 5.1.7 on 2025-04-16 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapi_app', '0003_remove_match_end_time_remove_match_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='statistics', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('games_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('games_lost', models.IntegerField(default=0)),
                ('points_scored', models.IntegerField(default=0)),
                ('points_conceded', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(default=0.0)),
                ('best_win_streak', models.IntegerField(default=0)),
                ('worst_lose_streak', models.IntegerField(default=0)),
                ('c_win_streak', models.IntegerField(default=0)),
                ('c_lose_streak', models.IntegerField(default=0)),
                ('nb_tournaments_played', models.IntegerField(default=0)),
                ('nb_tournaments_won', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stats_history', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'player_statistics',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
