# Generated by Django 5.1.7 on 2025-03-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapi_app', '0003_player_two_fa_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='two_fa_verified',
        ),
    ]
