services:
  user:
    container_name: ctn_user
    build :
      context: ../ # ! FUCKING DO NOT TOUCH THIS, I LOST 5 LIFETIME YEARS ON THIS
      dockerfile: _docker/Dockerfile
    environment:
      env: prod
      name: user
      port: $user_port
      HOST_IP: $HOST_IP     
      DJANGO_SETTINGS_MODULE: user.settings # usefull ??
    env_file:
      - ../../.env
    image: img_user
    networks:
      - transcendence_network
    volumes:
      - staticvol:/app/staticfiles
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:${user_port}/health/ > /dev/null 2>&1"]
      interval: 10s    # How often to run the health check (every 90 seconds)
      timeout: 2s       # Maximum time to wait for the check to complete
      retries: 10         # Number of consecutive failures needed to mark container as unhealthy
      start_period: 60s  # Initial grace period where failures don't count (container startup time)
    restart: always