services:
  nginx:
    build:
      args:
        env: dev
    volumes:
      - ./staticfiles:/usr/share/nginx/static   

  static_files:
    environment:
      - env=dev
      - HOST_IP=${HOST_IP}
    ports:
      - "${static_files_port}:${static_files_port}"
    volumes:    
      - ./static_files:/app/

  tournament:
    build:
      context: ./tournament
      dockerfile: _docker/Dockerfile
    environment:
      - env=dev
      - HOST_IP=${HOST_IP}
    ports:
      - "${tournament_port}:${tournament_port}"
    volumes:
      - ./tournament:/app/

  user:
    build:
      context: ./user
      dockerfile: _docker/Dockerfile
    environment:
      - env=dev
      - HOST_IP=${HOST_IP}
    env_file:
      - .env
    ports:
      - "${user_port}:${user_port}"
    volumes:
      - ./user:/app/

  match:
    build:
      context: ./match
      dockerfile: _docker/Dockerfile
    environment:
      - env=dev
      - HOST_IP=${HOST_IP}
    ports:
      - "${match_port}:${match_port}"
    volumes:
      - ./match:/app/


  databaseapi:
    build:
      context: ./databaseapi
      dockerfile: _docker/Dockerfile
    environment:
      - env=dev
      - HOST_IP=${HOST_IP}
    ports:
      - "${databaseapi_port}:${databaseapi_port}"
    volumes:
      - ./databaseapi:/app/

  api_gateway:
    environment:
      - env=dev
      - HOST_IP=${HOST_IP}
    ports:
      - "${api_gateway_port}:${api_gateway_port}"
    volumes:
      - ./api_gateway:/app/
